name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install runtime and dev dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          echo 'Installing runtime requirements...'
          pip install -r requirements.txt
        else
          echo 'No runtime requirements file found.'
        fi
        if [ -f requirements-dev.txt ]; then
          echo 'Installing developer/test requirements...'
          pip install -r requirements-dev.txt
        else
          echo 'No dev requirements file found.'
        fi
        if [ ! -f requirements.txt -a ! -f requirements-dev.txt ]; then
          pip install pytest
        fi
    
    - name: Lint with flake8
      run: |
        cd backend
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test with pytest
      run: |
        cd backend
        pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
