name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-tests:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            C:\\Users\\runneradmin\\AppData\\Local\\pip\\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m venv .venv
          .venv\\Scripts\\python -m pip install --upgrade pip
          .venv\\Scripts\\python -m pip install -r requirements.txt
          .venv\\Scripts\\python -m pip install pytest pytest-asyncio pytest-cov

      - name: Run backend tests
        working-directory: backend
        env:
          TRANSFORMERS_OFFLINE: '1'
          HF_HUB_DISABLE_TELEMETRY: '1'
        run: |
          .venv\\Scripts\\python -m pytest -v

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-htmlcov
          path: backend/htmlcov
